
services:
  redis:
    image: redis/redis-stack:latest
    ports:
      - 6379:6379
      - 8001:8001
    networks:
      - redisnet
    volumes:
      - redisinsight_db:/db
    networks:
      - redisnet

volumes:
  redisinsight_db: 
  
networks:
  redisnet:
    external: true 
